---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s-one-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.120-192.168.0.130
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k3s-one
  namespace: metallb-system
